let stockDeProductos = [
	{
		id: 1,
		nombre: "Pad 1",
		tipo: "LBlackPad",
		precio: 8000,
		img: (src = "./images/pad1.webp"),
		cantidad: 1,
	},
	{
		id: 2,
		nombre: "Pad 2",
		tipo: "BluePad",
		precio: 6000,
		img: (src = "./images/pad2.webp"),
		cantidad: 1,
	},
	{
		id: 3,
		nombre: "Pad 3",
		tipo: "BlackPad",
		precio: 7000,
		img: (src = "./images/pad3.webp"),
		cantidad: 1,
	},
	{
		id: 4,
		nombre: "Pad 4",
		tipo: "PinkPad",
		precio: 6500,
		img: (src = "./images/pad4.webp"),
		cantidad: 1,
	},
	{
		id: 5,
		nombre: "Pad 5",
		tipo: "RedPad",
		precio: 7500,
		img: (src = "./images/pad5.webp"),
		cantidad: 1,
	},
];
